### PR TITLE
Add spanish and italian translation

### PR DESCRIPTION
**Pull request by Maks-s**
Add spanish and italian translation from the web archive.
Some sentences are translated using deepl.com

Also, move langs/\*_{lang}.\* to langs/{lang}/\*.\* for better readability

As a side-note, politiscale is mainly a browser-based quiz, so I was thinking about rewriting it in something like Vue / Nuxt, what do you think ?

### CODE REVIEW

**Comment by Donokami** [comment]
Thanks a lot for the translation and contributions!

For the Vue rewrite, that would be a good idea, but I'm not sure if it would be useful and/or helping for performances/readability.
You would keep PHP for the backend in this setup?

**Comment by Maks-s** [comment]
As the quiz is done in the browser and doesn't need a back-end, loading only one Vue app should be quicker than navigating a whole website made in PHP, as well as being more readable and maintainable than having one part in PHP and the other in JS (translations, for example)

I wouldn't keep the PHP back-end as it isn't needed, though the statistics could be very easily implemented by sending/receiving stats from an endpoint

**Comment by Donokami** [comment]
> As the quiz is done in the browser and doesn't need a back-end, loading only one Vue app should be quicker than navigating a whole website made in PHP, as well as being more readable and maintainable than having one part in PHP and the other in JS (translations, for example)

The PHP implementation is only there to deal with localization implementation, with SEO and social medias. The advanced Politiscales version (not the DBHQ one) was fully static, and used a static way to translate everything. On my implementation, the translation is made on the client-side, and the crawlers don't execute the JS (so you can't have a translated version of results to show on Twitter for example).

With Vue we could also switch to a SSR to get rid of PHP implementation, but I don't know if it would be worth it, between the performance gain/ease to ease of maintaining the project & code rewrite ratio. (I also don't have any big experience with JS!)

> I wouldn't keep the PHP back-end as it isn't needed, though the statistics could be very easily implemented by sending/receiving stats from an endpoint

Yep  definitely, Politiscales stats should be on an external endpoint, with its own independent project structure. I should add this to the roadmap!

**Comment by Maks-s** [comment]
> On my implementation, the translation is made on the client-side, and the crawlers don't execute the JS (so you can't have a translated version of results to show on Twitter for example).

You could add an URL parameter to translate to the specific language (or check the top-level domain), however, it would mean calculating some things (like the slogan) server-side, splitting the work between PHP and JS

> With Vue we could also switch to a SSR to get rid of PHP implementation

Good idea, also we could do SSR to display the result's flag on twitter, for example

> but I don't know if it would be worth it, between the performance gain/ease to ease of maintaining the project & code rewrite ratio.

For the performance aspect, neither do I, however the code rewrite shouldn't take very long as most of the website is already in JS (except if we decide to use TS), and it would make it easier to maintain because features wouldn't be split between server-side PHP and client-side JS

> (I also don't have any big experience with JS!)

No problem, we're all here to learn :)

**Comment by Maks-s** [comment]
Hey @Donokami, still interested in this rewrite thing ? Send me an email if you are, so we can discuss it ;)

**Pull request merged**
